apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdfdftnj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdfdftnj
  template:
    metadata:
      labels:
        app: mdfdftnj
    spec:
      containers:
      - image: okteto.dev/mdfdftnj:latest
        name: mdfdftnj
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "31dde201-eec9-441c-8932-bcb7d8a395f8"
        - name: Vless_Path
          value: "/jkduij897"
        - name: Vmess_UUID
          value: "31dde201-eec9-441c-8932-bcb7d8a395f8"
        - name: Vmess_Path
          value: "/uiytre345"
        - name: Share_Path
          value: "/v2link"
